workspace(name = "protobuf_bug")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_protobuf",
  urls = ["https://github.com/google/protobuf/archive/v3.6.1.3.zip"],
  strip_prefix = "protobuf-3.6.1.3",
)
